on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # your build step here
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Site
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          NEKOWEB_API_KEY: ${{ secrets.NEKOWEB_API_KEY }}
          NEKOWEB_COOKIE: ${{ secrets.NEKOWEB_COOKIE }}
        run: |
          npm run build
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@v1.0.0
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: '/anniesden.dev/'
          directory: 'build'
